version: "3.4"

services:

  api_pdv_change:
    image: marciomendes/apipdvchange
    restart: always
    build:
      context: .
      dockerfile: api_pdv_change/Dockerfile
    links:
      - db_pgsql
    depends_on:
      - db_pgsql
    ports:
      - "0.0.0.0:32800:443"
    networks:
      - api-pdv-network

  db_pgsql:
    image: postgres
    environment:
      - POSTGRES_DB=api_pdv_docker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"
    networks:
      - api-pdv-network

networks:
  api-pdv-network:
    driver: bridge